### ISSUE TITLE
Unable to attach JSON response in the report

### ISSUE THREAD

**Issue by varshanharshank** [WasiqB/multiple-cucumber-html-reporter#328]
**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: [e.g. 1.10.0] - 3.6.0
 - Node.js version: [e.g. 8.9.1]- v18.17.1
 - NPM version: [e.g. 5.8.0] - v18.17.1
 - Platform name and version: [e.g. Windows 10] - mac sonoma 14.4
 - Cucumber version: [e.g. 4.2.0]  - 9.3.0

**Config of multiple-cucumber-html-reporter**
An example of how you configured the reporter in your config

import report = require('multiple-cucumber-html-reporter')
report.generate({
  jsonDir: 'reports/cucumberReport',
  reportName: 'Portal Report',
  reportPath: './reports/cucumberReport',
  metadata: {
    browser: {
      name: '',
      version: '',
    },
    device: 'Local test machine',
    platform: {
      name: '',
      version: '',
    },
  },
  customData: {
    title: 'Run info',
    data: [
      { label: 'Project', value: 'Test' },
      { label: 'Application', value: 'Portal' },
    ],
  },
})

**Describe the bug**
Try to attach the json log in the step definition and it is not attaching in the multiple-cucumber-html-reporter. But it is working fine in the normal cucumber report

/Users/test/Documents/Workspace/miscellaneous/PurpleRouter/node_modules/multiple-cucumber-html-reporter/lib/generate-report.js:406
    scenario.steps.forEach((step) => {
                   ^
SyntaxError: Unexpected token i in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/test/Documents/Workspace/miscellaneous/PurpleRouter/node_modules/multiple-cucumber-html-reporter/lib/generate-report.js:425:24
    at Array.forEach (<anonymous>)
    at /Users/test/Documents/Workspace/miscellaneous/PurpleRouter/node_modules/multiple-cucumber-html-reporter/lib/generate-report.js:409:25
    at Array.forEach (<anonymous>)
    at _parseSteps (/Users/test/Documents/Workspace/miscellaneous/PurpleRouter/node_modules/multiple-cucumber-html-reporter/lib/generate-report.js:406:20)
    at /Users/test/Documents/Workspace/miscellaneous/PurpleRouter/node_modules/multiple-cucumber-html-reporter/lib/generate-report.js:328:18
    at Array.forEach (<anonymous>)
    at _parseScenarios (/Users/test/Documents/Workspace/miscellaneous/PurpleRouter/node_modules/multiple-cucumber-html-reporter/lib/generate-report.js:318:22)
    at /Users/test/Documents/Workspace/miscellaneous/PurpleRouter/node_modules/multiple-cucumber-html-reporter/lib/generate-report.js:226:17
    
    
But i could see json response in the normal cucumber report

![image](https://github.com/WasiqB/multiple-cucumber-html-reporter/assets/81335781/023c7617-d3f7-4273-a5c5-b0bd8755c6c8)

**To Reproduce**

1. Try to attach any of json response in the cucmeber step definion
<img width="787" alt="image" src="https://github.com/WasiqB/multiple-cucumber-html-reporter/assets/81335781/330730a1-ad97-47ca-94be-6ac63301aec9">
2. Run the following command to generate report and observe

npx ts-node src/helper/report/cucumberReport.ts
3. observe the error

[Include code or an example repository that can easily be set up]

**Expected behavior**
It should not throw error and able to generate reprot

**Log**
If applicable, add logs to help explain your problem. If you don't have logs, enable 'debug:true' in the config and paste the log here.
Please use proper markdown to style it

**Additional context**

**Comment by varshanharshank** [comment]
@WasiqB  please look into this report

**Comment by varshanharshank** [comment]
@WasiqB do you have any update about this issue

**Comment by WasiqB** [comment]
Hi @varshanharshank ,

Try using the new version [4.0.0-beta.0](https://github.com/WasiqB/multiple-cucumber-html-reporter/releases/tag/v4.0.0-beta.0) and check if this issue is fixed with the new report.

You can refer to the [attachment documentation](https://multiple-cucumber-html-reporter.vercel.app/docs/attachments) on how to attach JSON string.
